# Generated by Django 5.1.6 on 2025-02-15 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyter', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='id_instituicao',
            field=models.ForeignKey(blank=True, db_column='id_instituicao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pyter.instituicoes'),
        ),
    ]
