# Generated by Django 5.1.6 on 2025-04-10 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyter', '0003_itenspedido_adicionais_alter_itenspedido_id_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='nome',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='instituicoes',
            old_name='nome',
            new_name='instituicao',
        ),
        migrations.RenameField(
            model_name='materiais',
            old_name='nome',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='nome',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='situacoes',
            old_name='nome',
            new_name='situacao',
        ),
        migrations.AddField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clientes',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='cod_rastreamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='data_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='modalidade',
            field=models.CharField(choices=[('PR', 'Presencial'), ('ON', 'Online')], default='PR', max_length=2),
        ),
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='pyter.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('meio_pagamento', models.CharField(choices=[('Caixa', 'Caixa'), ('PicPay', 'PicPay'), ('Mercado Pago', 'Mercado Pago'), ('PagBank', 'PagBank'), ('Sumup', 'Sumup')], max_length=30)),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Pix', 'Pix'), ('Crédito', 'Crédito'), ('Débito', 'Débito')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('cod_autorizacao', models.CharField(blank=True, max_length=50, null=True)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='pyter.pedidos')),
            ],
        ),
    ]
