# Generated by Django 5.1.6 on 2025-04-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyter', '0004_rename_nome_categorias_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenspedido',
            name='descontos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
