# Generated by Django 5.1.6 on 2025-04-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyter', '0005_itenspedido_descontos_pedidos_valor_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenspedido',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
