# Generated by Django 5.1.6 on 2025-04-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyter', '0006_itenspedido_preco_unitario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itenspedido',
            old_name='preco_unitario',
            new_name='preco_unitario_base',
        ),
    ]
