# Generated by Django 5.1.6 on 2025-04-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyter', '0007_rename_preco_unitario_itenspedido_preco_unitario_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenspedido',
            name='observacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
