# Generated by Django 5.1.6 on 2025-04-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyter', '0008_itenspedido_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentos',
            name='parcelas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='modalidade',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Online', 'Online')], default='Presencial', max_length=20),
        ),
    ]
